analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # since this is just an example, there is no need for ubiquitous documentation.
    public_member_api_docs: false

