name: bloc_example
description: "An example of a Flutter project combining disco and bloc."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  disco:
    path: ../../packages/disco
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
