include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # simple todos are fine
    flutter_style_todos: false
    # since this is just an example, there is no need for ubiquitous documentation.
    public_member_api_docs: false